name: PlayerStatsMenu
version: '1.0.0'
main: io.Sriptirc_wp_1.playerstatsmenu.Playerstatsmenu
api-version: '1.16'
authors: ['wp:1']
description: '一个查看玩家血量、护甲、移动速度等状态信息的菜单插件'
commands:
    stats:
        description: '打开玩家状态信息菜单'
        aliases: ['mystats', 'psm']
permissions:
    playerstatsmenu.use:
        description: '使用玩家状态菜单插件'
        default: true
    playerstatsmenu.admin:
        description: '管理玩家状态菜单插件'
        default: op
