name: NoPhantom
version: '1.0.0'
main: io.Sriptirc_wp_1.nophantom.Nophantom
api-version: '1.16'
authors: ['wp:1']
description: '禁止幻翼生成的插件'
commands:
    nophantom:
        description: 'NoPhantom插件主命令'
        aliases: ['np']
permissions:
    nophantom.use:
        description: '使用NoPhantom插件命令'
        default: false
    nophantom.admin:
        description: '管理NoPhantom插件配置'
        default: false
    nophantom.bypass:
        description: '绕过幻翼生成限制'
        default: false
